### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by Morayabb** [XY-boy/TTST#4]
Thank you very much for your excellent work. But here, I have a question I want to consult, about the inference stage of the matrics calculation I have not seen in the existing code, may I ask which code is used to achieve it? If you are free, please reply, thank you!

**Comment by XY-boy** [comment]
> Thank you very much for your excellent work. But here, I have a question I want to consult, about the inference stage of the matrics calculation I have not seen in the existing code, may I ask which code is used to achieve it? If you are free, please reply, thank you!

Hi. The code of metric calculation has been upload. https://github.com/XY-boy/TTST/tree/35853bf30b81edf5709dfd33738b47572ecd2496/metrics

**Comment by Morayabb** [comment]
Thanks！
